{application, ${ARTIFACT},
  [{description, ${DESCRIPTION}},
   {id, ${ID}},
   {vsn, ${VERSION}},
   {modules, ${MODULES}},
   {maxT, infinity},
   {registered, ${REGISTERED}},
   {included_applications, []},
   {applications, [kernel,stdlib,${APPLICATIONS}]},
   {env, [{prefer_ipv6, false}]},
   {start_phases, []}]}.